ifnine_core/urls.py
from django.urls import path, include
from ifnine_core.views import index, category_list_view, category_product_list_view, product_list_view, vendor_list_view, vendor_detail_view, product_detail_view, tag_list, ajax_add_review, search_view, filter_product, add_to_cart, cart_view, delete_item_from_cart, update_cart, checkout_view, payment_completed_view, payment_failed_view, customer_dashboard, user_history, order_detail, make_address_default, add_to_wishlist, wishlist_view, contact, ajax_contact_form, remove_from_wishlist, user_profile

app_name = 'core'

urlpatterns=[
    # Homepage
    path('', index, name='index'),
    path('products/', product_list_view, name='product-list'),
    path('products/<pid>/', product_detail_view, name='product-detail'),
    
    
    # category
    path('category/', category_list_view, name='category-list'),
    path('category/<cid>/', category_product_list_view, name='category-product-list'),
    
    # vendor
    path('vendors/', vendor_list_view, name='vendor-list'),
    path('vendor/<vid>/', vendor_detail_view, name='vendor-detail'),
    
    # Tags
    path('products/tag/<slug:tag_slug>/', tag_list, name='tags'),
    
    # Reviews
    path('ajax-add-review/<int:pid>/', ajax_add_review, name='ajax-add-review'),
    
    # Search
    path('search/', search_view, name='search'),
    
    # Filter product URL
    path('filter-products/', filter_product, name='filter-product'),
    
    #Add to cart URL
    path('add-to-cart/', add_to_cart, name='add-to-cart'),
    
    # Cart page URL
    path('cart/', cart_view, name='cart'),
    
    # Delete item from cart
    path('delete-from-cart/', delete_item_from_cart, name='delete-from-cart'),
    
    # Update items in cart
    path('update-cart/', update_cart, name='update-cart'),
    
    # checkout url
    path('checkout/', checkout_view, name='checkout'),
    
    # Paypal URL
    path('paypal/', include('paypal.standard.ipn.urls')),
    
    # Payment succesful
    path('payment-completed/', payment_completed_view, name='payment-completed'),
    
    # checkout url
    path('payment-failed/', payment_failed_view, name='payment-failed'),
    
    # User Dashboard
    path('user-profile/', user_profile, name='user-profile'),
    
    # User Dashboard
    path('dashboard/', customer_dashboard, name='dashboard'),
    
    # User History
    path('user-history/', user_history, name='user-history'),
    
    # Order detail
    path('user-history/order/<int:id>', order_detail, name='order-detail'),
    
    # Making address default
    path('make-default-address', make_address_default, name='make-default-address'),
    
     # Wishlist page URL
    path('wishlist/', wishlist_view, name='wishlist'),
    
    # Adding to wishlist
    path('add-to-wishlist/', add_to_wishlist, name='add-to-wishlist'),
    
    # Deleting from wishlist
    path('remove-from-wishlist/', remove_from_wishlist, name='remove-from-wishlist'),
    
    # Making address default
    path('contact/', contact, name='contact'),
    path('ajax-contact-form/', ajax_contact_form, name='ajax-contact-form'),
]

ifnine_stores/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("ifnine_core.urls")),
    path('user/', include("django.contrib.auth.urls")),
    path('user/', include("userauths.urls")),
    
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
urlpatterns += staticfiles_urlpatterns()

userauths/urls.py
from django.urls import path
from userauths import views


app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),
    
    path("profile/update/", views.profile_update, name="profile-update"),
]

templates/core/dashboard.html
{% extends 'partials/base.html' %}
{% load static %}

{% block page_title %}iFNINE STORES | User Profile {% endblock %}

{% block content %}


     <!-- Main Style -->
     <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" /> 
     <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}" />
  
      <!-- Background css -->
     <link rel="stylesheet" id="bg-switcher-css" href="{% static 'assets/css/backgrounds/bg-4.css' %}"> 
     

<main class="main-content" id="cart-list">


    <!-- Ec breadcrumb start -->
    <div class="sticky-header-next-sec  ec-breadcrumb section-space-mb">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="row ec_breadcrumb_inner">
                        <div class="col-md-6 col-sm-12">
                            <h2 class="ec-breadcrumb-title">User Dashboard</h2>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <!-- ec-breadcrumb-list start -->
                            <ul class="ec-breadcrumb-list">
                                <li class="ec-breadcrumb-item"><a href="index.html">Home</a></li>
                                <li class="ec-breadcrumb-item active">Dashboard</li>
                            </ul>
                            <!-- ec-breadcrumb-list end -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Ec breadcrumb end -->

    <!-- User profile section -->
    <section class="ec-page-content ec-vendor-uploads ec-user-account section-space-p">
        <div class="container">
            <div class="row">
                <!-- Sidebar Area Start -->
                <div class="ec-shop-leftside ec-vendor-sidebar col-lg-3 col-md-12">
                    <div class="ec-sidebar-wrap ec-border-box">
                        <!-- Sidebar Category Block -->
                        <div class="ec-sidebar-block">
                            <div class="ec-vendor-block">
                                <!-- <div class="ec-vendor-block-bg"></div>
                                <div class="ec-vendor-block-detail">
                                    <img class="v-img" src="{% static 'assets/images/user/1.jpg' %}" alt="vendor image">
                                    <h5>Mariana Johns</h5>
                                </div> -->
                                <div class="ec-vendor-block-items">
                                    <ul>
                                        <li><a href="{% url 'core:user-profile' %}">User Profile</a></li>
                                        <li><a href="{% url 'core:user-history' %}">History</a></li>
                                        <li><a href="{% url 'core:wishlist' %}">Wishlist</a></li>
                                        <li><a href="{% url 'core:cart' %}">Cart</a></li>
                                        <li><a href="{% url 'core:checkout' %}">Checkout</a></li>
                                        <li><a href="{% url 'userauths:sign-out' %}">Logout</a></li>
                                        {% comment %} <li><a href="track-order.html">Track Order</a></li> {% endcomment %}
                                        {% comment %} <li><a href="{% url 'core:payment-completed' %}">Invoice</a></li> {% endcomment %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="ec-shop-rightside col-lg-9 col-md-12">
                    <div class="ec-vendor-dashboard-card ec-vendor-setting-card">
                        
                        <div class="ec-vendor-card-body">
                            
                            <div class="row">
                                
                                <div class="col-md-12">
                                    
                                    <div class="ec-vendor-block-profile">
                                        
                                        <div class="ec-vendor-block-img space-bottom-30">
                                            
                                            <p>Hello <span>{{ request.user|title }}!</span></p>
                                            <p>From your account you can easily view and track your orders. You can manage and change your account information like address and your contact information</p>
                                        </div>
                                        
                                        <h5>Delivery Information</h5>

                                        <div>
                                            <canvas style="height: 50px;" id="myChart"></canvas>
                                        </div>

                                        <form class="mb-4" method="POST">
                                            {% csrf_token %}
                                            <div class="card-hdeader">
                                                <h5>Add Address</h5>
                                            </div>
                                            <div class="row">
                                                <div class="form-group col-md-6">
                                                    <input placeholder="Address" required="" class="form-control" name="address" type="text" />
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <input placeholder="Mobile" required="" class="form-control" name="mobile" />
                                                </div>
                                            </div>
                                            <span><br></span>
                                            <div class="ec-check-order-btn mb-6">
                                                <button type="submit" class="btn btn-primary" name="submit" value="Submit">Save Address</button>
                                            </div>
                                        </form>

                                        <div class="row">
                                            
                                            {% for a in address %}
                                            <div class="col-md-6 col-sm-12">
                                                <p><strong>Address {{ forloop.counter }}: </strong>{{ a.address }}</p>
                                                <p><strong>Mobile : </strong>{{ a.mobile }}</p>
                                                {% if a.status %}
                                                    <i data-address-id="{{ a.id }}" class="ecicon eci-check-circle text-success check{{ a.id }} check"></i>
                                                    <button data-address-id="{{ a.id }}" style="display:none;" class="btn btn-primary make-default-address button{{ a.id }} action_btn">Make Default</button>
                                                {% else %}
                                                    <i data-address-id="{{ a.id }}" style="display:none;" class="ecicon eci-check-circle text-success check{{ a.id }} check"></i>
                                                    <button data-address-id="{{ a.id }}" class="btn btn-primary make-default-address button{{ a.id }} action_btn">Make Default</button>
                                                {% endif %}
                                            </div>
                                            {% endfor %} 
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End User profile section -->

</main>


<script>
    const labels = {{ month|safe }}
    const data = {
        labels: labels,
        datasets: [{
            label: 'Orders',
            backgroundColor: 'rgb(67,111,255)',
            borderColor: 'rgb(25, 99, 132)',
            data: {{ total_orders|safe }}
        }]
    };

    const config = {
        type: 'bar',
        data: data,
        options: {}
    };
    const myChart = new Chart(
        document.getElementById('myChart'),
        config
    );
</script>
    
{% endblock content %}

templates/core/user-profile.html
{% extends 'partials/base.html' %}
{% load static %}

{% block page_title %}iFNINE STORES | User Profile {% endblock %}

{% block content %}


     <!-- Main Style -->
     <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" /> 
     <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}" />
  
      <!-- Background css -->
     <link rel="stylesheet" id="bg-switcher-css" href="{% static 'assets/css/backgrounds/bg-4.css' %}"> 
     

<main class="main-content" id="cart-list">

    <!-- Ec breadcrumb start -->
    <div class="sticky-header-next-sec  ec-breadcrumb section-space-mb">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="row ec_breadcrumb_inner">
                        <div class="col-md-6 col-sm-12">
                            <h2 class="ec-breadcrumb-title">User Profile</h2>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <!-- ec-breadcrumb-list start -->
                            <ul class="ec-breadcrumb-list">
                                <li class="ec-breadcrumb-item"><a href="index.html">Home</a></li>
                                <li class="ec-breadcrumb-item active">Profile</li>
                            </ul>
                            <!-- ec-breadcrumb-list end -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Ec breadcrumb end -->

    <!-- User profile section -->
    <section class="ec-page-content ec-vendor-uploads ec-user-account section-space-p">
        <div class="container">
            <div class="row">
                <!-- Sidebar Area Start -->
                <div class="ec-shop-leftside ec-vendor-sidebar col-lg-3 col-md-12">
                    <div class="ec-sidebar-wrap ec-border-box">
                        <!-- Sidebar Category Block -->
                        <div class="ec-sidebar-block">
                            <div class="ec-vendor-block">
                                
                                <div class="ec-vendor-block-items">
                                    <ul>
                                        <li><a href="{% url 'core:dashboard' %}">Dashboard</a></li>
                                        <li><a href="{% url 'core:user-history' %}">History</a></li>
                                        <li><a href="{% url 'core:wishlist' %}">Wishlist</a></li>
                                        <li><a href="{% url 'core:cart' %}">Cart</a></li>
                                        <li><a href="{% url 'core:checkout' %}">Checkout</a></li>
                                        <li><a href="{% url 'userauths:sign-out' %}">Logout</a></li>
                                        {% comment %} <li><a href="track-order.html">Track Order</a></li> {% endcomment %}
                                        {% comment %} <li><a href="user-invoice.html">Invoice</a></li> {% endcomment %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="ec-shop-rightside col-lg-9 col-md-12">
                    <div class="ec-vendor-dashboard-card ec-vendor-setting-card">
                        <div class="ec-vendor-card-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="ec-vendor-block-profile">
                                        <div class="ec-vendor-block-img space-bottom-30">
                            
                                            <div class="ec-vendor-block-detail border-bottom">
                                                {% if profile.image %}
                                                    <img class="v-img" src="{{ profile.image.url }}" alt="user image">
                                                {% else %}
                                                    <img class="v-img" src="{% static 'assets/images/user/1.jpg' %}" alt="user image">
                                                {% endif %}
                                                <h5 class="name">{{ profile.full_name|title }}</h5>
                                                {% comment %} <p>( Business Man )</p> {% endcomment %}
                                            </div>
                                            <p>Hello <span>{{ request.user|title }}!</span></p>
                                            <p>From your account you can easily view and track orders. You can manage and change your account information like address, contact information and history of orders.</p>
                                        </div>
                                        <h5>Account Information</h5>
                                        
                                        <div class="row">
                                            <div class="col-md-6 col-sm-12">
                                                <div class="ec-vendor-detail-block ec-vendor-block-email space-bottom-30">
                                                    <h6>Full Name <a href="javasript:void(0)" data-link-action="editmodal" title="Edit Detail" data-bs-toggle="modal" data-bs-target="#edit_modal"></a></h6>
                                                    <ul>
                                                        <li><input class="border-none"  style="font-weight: 500; color: #777;" type="text" value="{{ profile.full_name }}"></li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="col-md-6 col-sm-12">
                                                <div class="ec-vendor-detail-block ec-vendor-block-contact space-bottom-30">
                                                    <h6>Bio<a href="javasript:void(0)" data-link-action="editmodal" title="Edit Detail" data-bs-toggle="modal" data-bs-target="#edit_modal"></a></h6>
                                                    <ul>
                                                        <li><input class="border-none" style="font-weight: 500; color: #777;" type="text" value="{{ profile.bio }}"></li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="col-md-6 col-sm-12">
                                                <div class="ec-vendor-detail-block ec-vendor-block-address mar-b-30">
                                                    <h6>Phone Number<a href="javasript:void(0)" data-link-action="editmodal" title="Edit Detail" data-bs-toggle="modal" data-bs-target="#edit_modal"></i></a></h6>
                                                    <ul>
                                                        <li><input class="border-none" style="font-weight: 500; color: #777;" type="text" value="{{ profile.phone }}"></li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="col-md-6 col-sm-12">
                                                <div class="ec-vendor-detail-block ec-vendor-block-address">
                                                    <h6>Verified<a href="javasript:void(0)" data-link-action="editmodal" title="Edit Detail" data-bs-toggle="modal"></a></h6>
                                                    {% if profile.verified == True %}
                                                    <ul>
                                                        <li><i class="fi-rr-check-circle"></i></li>
                                                    </ul>
                                                    {% else %}
                                                    <ul>
                                                        <li><i class="fi-rr-x" style="font-weight: 500; color: #777;"></i></li>
                                                    </ul>

                                                    {% endif %}

                                                </div>
                                            </div>
                                            <div>
                                                <button class="btn btn-lg btn-primary"><a href="{% url 'userauths:profile-update' %}">Edit Detail</a></button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End User profile section -->

  
</main>

    
{% endblock content %}

templates/core/wishlist.html
{% extends 'partials/base.html' %}
{% load static %}

{% block page_title %}iFNINE STORES | Wishlist {% endblock %}

{% block content %}


     <!-- Main Style -->
     <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" /> 
     <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}" />
  
      <!-- Background css -->
     <link rel="stylesheet" id="bg-switcher-css" href="{% static 'assets/css/backgrounds/bg-4.css' %}"> 

<main class="main-content" id="wishlist-list">

    <!-- Ec breadcrumb start -->
    <div class="sticky-header-next-sec  ec-breadcrumb section-space-mb">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="row ec_breadcrumb_inner">
                        <div class="col-md-6 col-sm-12">
                            <h2 class="ec-breadcrumb-title">Wishlist</h2>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <!-- ec-breadcrumb-list start -->
                            <ul class="ec-breadcrumb-list">
                                <li class="ec-breadcrumb-item"><a href="{% url 'core:index' %}">Home</a></li>
                                <li class="ec-breadcrumb-item active">Wishlist</li>
                            </ul>
                            <!-- ec-breadcrumb-list end -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Ec breadcrumb end -->

    <!-- User history section -->
    <section class="ec-page-content ec-vendor-uploads ec-user-account wishlist-2 section-space-p">
        <div class="container">
            <div class="row">
                <!-- Sidebar Area Start -->
                <div class="ec-shop-leftside ec-vendor-sidebar col-lg-3 col-md-12">
                    <div class="ec-sidebar-wrap">
                        <!-- Sidebar Category Block -->
                        <div class="ec-sidebar-block">
                            <div class="ec-vendor-block">
                                <div class="ec-vendor-block-items">
                                    <ul><li><a href="{% url 'core:user-profile' %}">User Profile</a></li>
                                        <li><a href="{% url 'core:dashboard' %}">Dashboard</a></li>
                                        <li><a href="{% url 'core:user-history' %}">History</a></li>
                                        <li><a href="{% url 'core:cart' %}">Cart</a></li>
                                        <li><a href="{% url 'core:checkout' %}">Checkout</a></li>
                                        <li><a href="{% url 'userauths:sign-out' %}">Logout</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="ec-shop-rightside col-lg-9 col-md-12">
                    <div class="ec-vendor-dashboard-card">
                        <div class="ec-vendor-card-header">
                            <h5>Wishlist</h5>
                            <div class="ec-header-btn">
                                <a class="btn btn-lg btn-primary" href="{% url 'core:product-list' %}">Shop Now</a>
                            </div>
                        </div>
                        <div class="ec-vendor-card-body">
                            <div class="ec-vendor-card-table">
                                <table class="table ec-table">
                                    <thead>
                                        <tr>
                                            <th scope="col">ID</th>
                                            <th scope="col">Image</th>
                                            <th scope="col">Name</th>
                                            <th scope="col">Price</th>
                                            <th scope="col">Status</th>
                                            <th scope="col">Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody class="wish-empt">
                                        {% for w in w %}
                                        <tr class="pro-gl-content">
                                            <th scope="row"><span>{{ w.product.id }}</span></th>
                                            <td><img class="prod-img" src="{{ w.product.image.url }}"
                                                    alt="product image"></td>
                                            <td><span>
                                                <h6><a href="{% url 'core:product-detail' w.product.pid %}"> {{ w.product.title|truncatechars:20 }}</a></h6>
                                                </span></td>
                                            <td><span class="d-flex"><h6>₦</h6><h6 class="current-product-price-{{ w.product.id }}">{{ w.product.price }}</h6></span></td>
                                            <td><span class="avl">{% if w.product.in_stock %} Available {% else %}  Out of stock  {% endif %}</span></td>
                                            <td><span class="tbl-btn">
                                                <input type="hidden" value="1" name="" id="product-quantity" class="w-25 mb-20 product-quantity-{{w.product.id}}">
                                                <input type="hidden" class="product-pid-{{w.product.id}}" value="{{w.product.pid}}">
                                                <input type="hidden" class="product-image-{{w.product.id}}" value="{{w.product.image.url}}">
                                                <input type="hidden" class="product-id-{{w.product.id}}" value="{{ w.product.id }}">
                                                <input type="hidden" class="product-title-{{w.product.id}}" value="{{ w.product.title }}">
                                                <button class="btn btn-lg btn-primary add-to-cart-btn" data-index="{{ w.product.id }}" title="Add To Cart"> 
                                                    <i class="fi-rr-shopping-basket"></i>
                                                </button>
                                                <button class="btn btn-lg btn-primary delete-wishlist-product" data-wishlist-product="{{ w.id }}" title="Remove From List">×</button></span>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End User history section -->

</main>
{% endblock content %}