ifnine_core/urls.py
from django.urls import path, include
from ifnine_core.views import index, category_list_view, category_product_list_view, product_list_view, vendor_list_view, vendor_detail_view, product_detail_view, tag_list, ajax_add_review, search_view, filter_product, add_to_cart, cart_view, delete_item_from_cart, update_cart, checkout_view, payment_completed_view, payment_failed_view, customer_dashboard, user_history, order_detail, make_address_default, add_to_wishlist, wishlist_view, contact, ajax_contact_form, remove_from_wishlist, user_profile

app_name = 'core'

urlpatterns=[
    # Homepage
    path('', index, name='index'),
    path('products/', product_list_view, name='product-list'),
    path('products/<pid>/', product_detail_view, name='product-detail'),
    
    
    # category
    path('category/', category_list_view, name='category-list'),
    path('category/<cid>/', category_product_list_view, name='category-product-list'),
    
    # vendor
    path('vendors/', vendor_list_view, name='vendor-list'),
    path('vendor/<vid>/', vendor_detail_view, name='vendor-detail'),
    
    # Tags
    path('products/tag/<slug:tag_slug>/', tag_list, name='tags'),
    
    # Reviews
    path('ajax-add-review/<int:pid>/', ajax_add_review, name='ajax-add-review'),
    
    # Search
    path('search/', search_view, name='search'),
    
    # Filter product URL
    path('filter-products/', filter_product, name='filter-product'),
    
    #Add to cart URL
    path('add-to-cart/', add_to_cart, name='add-to-cart'),
    
    # Cart page URL
    path('cart/', cart_view, name='cart'),
    
    # Delete item from cart
    path('delete-from-cart/', delete_item_from_cart, name='delete-from-cart'),
    
    # Update items in cart
    path('update-cart/', update_cart, name='update-cart'),
    
    # checkout url
    path('checkout/', checkout_view, name='checkout'),
    
    # Paypal URL
    path('paypal/', include('paypal.standard.ipn.urls')),
    
    # Payment succesful
    path('payment-completed/', payment_completed_view, name='payment-completed'),
    
    # checkout url
    path('payment-failed/', payment_failed_view, name='payment-failed'),
    
    # User Dashboard
    path('user-profile/', user_profile, name='user-profile'),
    
    # User Dashboard
    path('dashboard/', customer_dashboard, name='dashboard'),
    
    # User History
    path('user-history/', user_history, name='user-history'),
    
    # Order detail
    path('user-history/order/<int:id>', order_detail, name='order-detail'),
    
    # Making address default
    path('make-default-address', make_address_default, name='make-default-address'),
    
     # Wishlist page URL
    path('wishlist/', wishlist_view, name='wishlist'),
    
    # Adding to wishlist
    path('add-to-wishlist/', add_to_wishlist, name='add-to-wishlist'),
    
    # Deleting from wishlist
    path('remove-from-wishlist/', remove_from_wishlist, name='remove-from-wishlist'),
    
    # Making address default
    path('contact/', contact, name='contact'),
    path('ajax-contact-form/', ajax_contact_form, name='ajax-contact-form'),
]

ifnine_stores/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("ifnine_core.urls")),
    path('user/', include("django.contrib.auth.urls")),
    path('user/', include("userauths.urls")),
    
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
urlpatterns += staticfiles_urlpatterns()

userauths/urls.py
from django.urls import path
from userauths import views


app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),
    
    path("profile/update/", views.profile_update, name="profile-update"),
]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save



# Create your models here.
class User(AbstractUser):
    email = models.EmailField(unique=True, null=False, blank=False)
    username = models.CharField(max_length=100)
    bio = models.CharField(max_length=100, null=True, blank=True)
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    
    def __str__(self):
        return self.username
    

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="image", null=True, blank=True)
    full_name = models.CharField(max_length=200, null=True, blank=True)
    bio = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=200, null=True, blank=True)
    verified = models.BooleanField(default=False)
    
    
    def __str__(self):
        return self.user.username


class ContactUs(models.Model):
    full_name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    phone = models.CharField(max_length=200)
    message = models.TextField()
    
    class Meta:
        verbose_name_plural = 'Contact Us'
    
    def __str__(self):
        return self.full_name
    
    
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
        
        
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()
    
post_save.connect(create_user_profile, sender=User)
post_save.connect(save_user_profile, sender=User)

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User, Profile


class UserRegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Username"})) 
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Email"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Password"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Confirm Password"}))

    class Meta:
        model = User
        fields = ["username", "email"]
        

class ProfileForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Full name"})) 
    # image = forms.ImageField(widget=forms.FileInput(attrs={"placeholder": "Image"}))
    bio = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Bio"}))
    phone = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Phone"}))
    
    class Meta:
        model = Profile
        fields = ['full_name', 'image', 'bio', 'phone']

userauths/views.py
from django.shortcuts import render, redirect
from userauths.forms import UserRegisterForm, ProfileForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.conf import settings
from django.contrib.auth.models import User
from userauths.models import Profile



User = settings.AUTH_USER_MODEL


# To register users
def register_view(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST or None)
        if form.is_valid():
            new_user = form.save()
            userame = form.cleaned_data.get('username')
            messages.success(request, f"Account created for {userame} successfully!")
            new_user = authenticate(username=form.cleaned_data['email'],
                                    password=form.cleaned_data['password1'],
                                    )
            login(request, new_user)
            return redirect("core:index")
        
    else:
        form = UserRegisterForm()
    
    context = {
        'form': form
    }
    return render(request, "userauths/sign-up.html", context)


# To login users
def login_view(request):
    if request.user.is_authenticated:
        messages.warning(request, f"You are already logged in")
        return redirect("core:index")
    
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")
        user = authenticate(request, email=email, password=password)
       
        if user is not None:
            login(request, user)
            messages.success(request, f"Welcome {user.username}!")   
            return redirect("core:index")
            
        else:
            messages.warning(request, f"User with {email} does not exist, Create an account")        
    
    return render(request, "userauths/sign-in.html")
            

# To logout users
def logout_view(request):
    logout(request)
    messages.success(request, "You logged out successfully!")
    return redirect("userauths:sign-in")


# To edit user profile
def profile_update(request):
    profile = Profile.objects.get(user=request.user)
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            new_profile = form.save(commit=False)
            new_profile.user = request.user
            new_profile.save()
            messages.success(request, "Profile updated successfully")
            return redirect("core:user-profile")
        
    else:
        form = ProfileForm(instance=profile)
    
    context = {
        'form': form,
        'profile': profile,
        
    }
    return render (request, "userauths/profile-edit.html", context)

templates/userauths/profile-edit.html
{% extends 'partials/base.html' %}
{% load static %}

{% block page_title %}iFNINE STORES | User Profile {% endblock %}

{% block content %}


     <!-- Main Style -->
     <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" /> 
     <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}" />
  
      <!-- Background css -->
     <link rel="stylesheet" id="bg-switcher-css" href="{% static 'assets/css/backgrounds/bg-4.css' %}"> 
     

<main class="main-content" id="cart-list">

    <!-- Ec breadcrumb start -->
    <div class="sticky-header-next-sec  ec-breadcrumb section-space-mb">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="row ec_breadcrumb_inner">
                        <div class="col-md-6 col-sm-12">
                            <h2 class="ec-breadcrumb-title">Update Profile</h2>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <!-- ec-breadcrumb-list start -->
                            <ul class="ec-breadcrumb-list">
                                <li class="ec-breadcrumb-item"><a href="index.html">Home</a></li>
                                <li class="ec-breadcrumb-item active">Update Profile</li>
                            </ul>
                            <!-- ec-breadcrumb-list end -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Ec breadcrumb end -->

    <!-- User profile section -->
    <section class="ec-page-content ec-vendor-uploads ec-user-account section-space-p">
        <div class="container">
            <div class="row">
                <!-- Sidebar Area Start -->
                <div class="ec-shop-leftside ec-vendor-sidebar col-lg-3 col-md-12">
                    <div class="ec-sidebar-wrap ec-border-box">
                        <!-- Sidebar Category Block -->
                        <div class="ec-sidebar-block">
                            <div class="ec-vendor-block">
                                <!-- <div class="ec-vendor-block-bg"></div>
                                <div class="ec-vendor-block-detail">
                                    <img class="v-img" src="{% static 'assets/images/user/1.jpg' %}" alt="vendor image">
                                    <h5>Mariana Johns</h5>
                                </div> -->
                                <div class="ec-vendor-block-items">
                                    <ul>
                                        <li><a href="{% url 'core:user-profile' %}">User Profile</a></li>
                                        <li><a href="{% url 'userauths:sign-out' %}">Logout</a></li>
                                        {% comment %} <li><a href="track-order.html">Track Order</a></li> {% endcomment %}
                                        {% comment %} <li><a href="user-invoice.html">Invoice</a></li> {% endcomment %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="ec-shop-rightside col-lg-9 col-md-12">
                    <div class="ec-vendor-dashboard-card ec-vendor-setting-card">
                        <div class="ec-vendor-card-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="ec-vendor-block-profile">
                                        <div class="ec-vendor-block-detail border-bottom">
                                            {% if profile.image %}
                                                <img class="v-img" src="{{ profile.image.url }}" alt="user image">
                                            {% else %}
                                                <img class="v-img" src="{% static 'assets/images/user/1.jpg' %}" alt="user image">
                                            {% endif %}
                                            <h5 class="name">{{ profile.full_name|title }}</h5>
                                            {% comment %} <p>( Business Man )</p> {% endcomment %}
                                        </div>
                                        
                                        <h5 class ="border-bottom mb-10">Update Profile</h5>
                                        {% if form.errors %}
                                        <div class= "alert-danger alert">
                                            <strong>{{ form.errors }}</strong>                                        
                                        </div>
                                        {% endif %}                                        
                                        <form class="edit-form" action="" method="POST" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <div class="form-frame" style="font-weight: 500; color: #777; border:2px;">
                                                {{form.full_name}}
                                            </div>
                                            <br>
                                            <div class="form-frame" style="font-weight: 500; color: #777; border:2px;">
                                                {{form.bio}}
                                            </div>
                                            <br>
                                            <div class="form-frame" style="font-weight: 500; color: #777; border:2px;">
                                                {{form.phone}}
                                            </div>
                                            <br>
                                            <div class="form-frame" style="font-weight: 500; color: #777; border:2px;">
                                                {{form.image}}
                                            </div>
                                            <br>
                                            <div>
                                                <button type="submit" class="btn btn-lg btn-primary">Submit</button>
                                            </div>                              
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                  
                </div> 
            </div>
        </div>
    </section>
    <!-- End User profile section -->

  
</main>

    
{% endblock content %}

templates/userauths/sign-in.html
{% extends 'partials/base.html' %}
{% load static %}

{% block page_title %}iFNINE STORES | Login {% endblock %}
{% block content %}



    <!-- Main Style -->
     <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
     <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}" />
 
     <!-- Background css -->
     <link rel="stylesheet" id="bg-switcher-css" href="{% static 'assets/css/backgrounds/bg-4.css' %}">


<!-- iFNINE breadcrumb start -->
<div class="sticky-header-next-sec  ec-breadcrumb section-space-mb">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="row ec_breadcrumb_inner">
                    <div class="col-md-6 col-sm-12">
                        <h2 class="ec-breadcrumb-title">Login</h2>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <!-- iFNINE-breadcrumb-list start -->
                        <ul class="ec-breadcrumb-list">
                            <li class="ec-breadcrumb-item"><a href="index.html">Home</a></li>
                            <li class="ec-breadcrumb-item active">Login</li>
                        </ul>
                        <!-- iFNINE-breadcrumb-list end -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- iFNINE breadcrumb end -->

<!-- iFNINE login page -->
<section class="ec-page-content section-space-p">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <div class="section-title">
                    <h2 class="ec-bg-title">Log In</h2>
                    <h2 class="ec-title">Log In</h2>
                </div>
            </div>
            <div class="ec-login-wrapper">
                <div class="ec-login-container">
                    <div class="ec-login-form">
                        <form action="" method="POST">
                            {% csrf_token %} 
                            <span class="ec-login-wrap">
                                <label>Email Address*</label>
                                <input type="text" name="email" placeholder="Email" required />
                            </span>
                            <span class="ec-login-wrap">
                                <label>Password*</label>
                                <input type="password" name="password" placeholder="Enter your password" required />
                            </span>
                            <span class="ec-login-wrap ec-login-fp">
                                <label><a href="#">Forgot Password?</a></label>
                            </span>
                            <span class="ec-login-wrap ec-login-btn">
                                <button class="btn btn-primary" type="submit" method="POST">Login</button>
                            </span>
                            <span class="ec-login-wrap ec-login-fp">
                                <label>Dont have an account?<a href="{% url 'userauths:sign-up' %}"> Register here.</a></label>
                            </span>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="footer-offer">
    <div class="container">
        <div class="row">
            <div class="text-center footer-off-msg">
                <span>Need measurements taken or products installed?</span><a href="#" target="_blank">Click here</a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/userauths/sign-up.html
{% extends 'partials/base.html' %}
{% load static %}

{% block page_title %}iFNINE STORES | Register{% endblock %}
{% block content %}

    <!-- Main Style -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}" />

    <!-- Background css -->
    <link rel="stylesheet" id="bg-switcher-css" href="{% static 'assets/css/backgrounds/bg-4.css' %}">


<!-- iFNINE breadcrumb start -->
<div class="sticky-header-next-sec  ec-breadcrumb section-space-mb">
   <div class="container">
       <div class="row">
           <div class="col-12">
               <div class="row ec_breadcrumb_inner">
                   <div class="col-md-6 col-sm-12">
                       <h2 class="ec-breadcrumb-title">Register</h2>
                   </div>
                   <div class="col-md-6 col-sm-12">
                       <!-- iFNINE-breadcrumb-list start -->
                       <ul class="ec-breadcrumb-list">
                           <li class="ec-breadcrumb-item"><a href="index.html">Home</a></li>
                           <li class="ec-breadcrumb-item active">Register</li>
                       </ul>
                       <!-- iFNINE-breadcrumb-list end -->
                   </div>
               </div>
           </div>
       </div>
   </div>
</div>
<!-- iFNINE breadcrumb end -->

<!-- iFNINE Register page -->
<section class="ec-page-content section-space-p">
   <div class="container">
       <div class="row">
           <div class="col-md-12 text-center">
               <div class="section-title">
                   <h2 class="ec-bg-title">Register</h2>
                   <h2 class="ec-title">Register</h2>
               </div>
               {% if form.errors %}
               <div class="alert alert-danger">
                    <strong>{{ form.errors }}</stong>
                </div>
                {% endif %}
           </div>
           <div class="ec-login-wrapper">
               <div class="ec-login-container">
                   <div class="ec-login-form">
                       <form method="POST" action="">
                            {% csrf_token %}
                            <span class="ec-login-wrap">
                               {{ form.username }}
                            </span>
                            <span class="ec-login-wrap">
                                {{ form.email }}
                            </span>
                            <span class="ec-login-wrap">
                                {{ form.password1 }}
                            </span>
                            <span class="ec-login-wrap">
                                {{ form.password2 }}
                            </span>
                            <span class="ec-login-wrap ec-login-fp">
                                <label>Already have an account?<a href="{% url 'userauths:sign-in' %}"> Sign in.</a></label>
                            </span>
                            <span class="ec-login-wrap ec-login-btn">
                               <button class="btn btn-primary" type="submit">Register</button>
                            </span>
                           
                        </form>
                    </div>
               </div>
           </div>
       </div>
   </div>
</section>

<div class="footer-offer">
   <div class="container">
       <div class="row">
           <div class="text-center footer-off-msg">
            <span>Need measurements taken or products installed?</span><a href="#" target="_blank">Click here</a>
           </div>
       </div>
   </div>
</div>

{% endblock content %}